name: agent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  msp:
    path: ../packages/msp
  flutter_riverpod: ^3.3.1
  appwrite: ^23.0.0
  google_fonts: ^8.0.2
  flutter_dotenv: ^6.0.0
  flutter_rust_bridge: 2.11.1
  rust:
    path: rust
  dart_appwrite: ^22.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
