name: agent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  msp:
    path: ../packages/msp
  flutter_riverpod: ^3.3.1
  appwrite: ^23.0.0
  google_fonts: ^8.0.2
  flutter_dotenv: ^6.0.0
  flutter_rust_bridge: 2.11.1
  rust:
    path: rust
  dart_appwrite: ^22.0.0
  path: ^1.9.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
