// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchfRFURY5HtpOLN4_BofaCnu_4xT1Gvg',
    appId: '1:876728981578:web:0f5742e10ec5f4c3cdaeb3',
    messagingSenderId: '876728981578',
    projectId: 'matrix-platform',
    authDomain: 'matrix-platform.firebaseapp.com',
    storageBucket: 'matrix-platform.firebasestorage.app',
    measurementId: 'G-6QX45R3YWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7ivaEpDJVbUO5lMKBm1Mow3quJpSb1g',
    appId: '1:876728981578:android:88ab43840199b366cdaeb3',
    messagingSenderId: '876728981578',
    projectId: 'matrix-platform',
    storageBucket: 'matrix-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhfwFwywvVMALicSPrlWXsCNUvUC3Etc',
    appId: '1:876728981578:ios:745a08ba0280cbcacdaeb3',
    messagingSenderId: '876728981578',
    projectId: 'matrix-platform',
    storageBucket: 'matrix-platform.firebasestorage.app',
    iosBundleId: 'com.hejitech.matrixProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhfwFwywvVMALicSPrlWXsCNUvUC3Etc',
    appId: '1:876728981578:ios:745a08ba0280cbcacdaeb3',
    messagingSenderId: '876728981578',
    projectId: 'matrix-platform',
    storageBucket: 'matrix-platform.firebasestorage.app',
    iosBundleId: 'com.hejitech.matrixProgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchfRFURY5HtpOLN4_BofaCnu_4xT1Gvg',
    appId: '1:876728981578:web:6b3cab8eed592d99cdaeb3',
    messagingSenderId: '876728981578',
    projectId: 'matrix-platform',
    authDomain: 'matrix-platform.firebaseapp.com',
    storageBucket: 'matrix-platform.firebasestorage.app',
    measurementId: 'G-01GH8VD122',
  );
}
