// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TaskUpdateEvent {
  final String taskId;
  final String? status;
  final String? assignedTo;
  final String? report;

  const TaskUpdateEvent({
    required this.taskId,
    this.status,
    this.assignedTo,
    this.report,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^ status.hashCode ^ assignedTo.hashCode ^ report.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskUpdateEvent &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          status == other.status &&
          assignedTo == other.assignedTo &&
          report == other.report;
}
